### ISSUE TITLE
payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by Markoporius** [AlgorithmLX/LGameModpack-Issues#10]
**Description:** у друга раньше все было нормально, подключался и играл, а сейчас на момент пускает и крашит. Что делать?
(https://cdn.discordapp.com/attachments/786526988113281054/990341311435513886/unknown.png) 

**Logs:**(https://gist.github.com/Markoporius/8b2ecb59c67005fca92cd74042f50273)

**Version**

Minecraft: 1.16.5

Forge: 1.16.5-forge-36.2.26

Modpack: Endless Rise v1.4.6

**Comment by AlgorithmLX** [comment]
@barmaxx

**Comment by BarMaxx** [comment]
Пусть попробует удалить мод Performant

**Comment by Markoporius** [comment]
> Пусть попробует удалить мод Performant

не помогло(https://gist.github.com/Markoporius/2b274c60d41503981ca5b430f7bcb9fb) Новый лог

**Comment by Markoporius** [comment]
Хост(я) переустановил сборку. И коннект неожиданно прошел в чем проблема я не понял
