### ISSUE TITLE
Не засчитывается квест на инженерии 

### ISSUE THREAD

**Issue by MagaNude** [AlgorithmLX/LGameModpack-Issues#11]
**Description:**  Скрафтил инженерный молот и книжку, но квест не засчитался 
**Logs:** 
**Version** 1.16.5

Minecraft: TL

Forge: 36.2.26

Modpack: 1.4.6

//Don't touch me!

@BarMaxx

**Comment by Kiri-Yoshikage** [comment]
На что конкретно не засчитывается квест? В следующий раз добавляй пожалуйста описание. На какой предмет?

**Comment by AlgorithmLX** [comment]
Если вы измените описание, открою заново

**Comment by AlgorithmLX** [comment]
Ну вообще, вместо TL, должна была быть 1.16.5, ну и ладно. Снова открыто.

**Comment by AlgorithmLX** [comment]
Закрыл
