### ISSUE TITLE
Краши в Мастер тех

### ISSUE THREAD

**Issue by FaRTeKIO** [AlgorithmLX/LGameModpack-Issues#12]
**Description:** При заходе в игру крашится с проблемой в моде Эсеншиал крафт 4

**Logs:** There your logs from gist.github.com or log file(lasted.log)

**Version** 

Minecraft: There MC version
[latest.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9127922/latest.log)

Forge: there Forge version

Modpack: последняя версия мастер тех

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by Kiri-Yoshikage** [comment]
попробуй переустановить сборку, должно помочь.. Эссеншиал вообще мод с приколом, от него можно постоянно краши и вылеты ожидать. А, и кстати, ты так-то перепутал что-то, и логи каким-то образом запихнул в версию майна. Не критично, но в следующий раз делай аккуратнее и по возможности заполняй все поля пожалуйста
