### ISSUE TITLE
Проблемы с запуском майнкрафта

### ISSUE THREAD

**Issue by MisherK5** [AlgorithmLX/LGameModpack-Issues#14]
**Description:** При заходе в майн крашит с ошибкой в моде Waila

**Logs:** There your logs from gist.github.com or log file(lasted.log)

[crash-2022-08-03_20.32.44-client.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9254932/crash-2022-08-03_20.32.44-client.txt)

Minecraft Version: 1.12.2

Forge Version: there Forge version (example: xx.xx.x.xxx)

Modpack Version: there Modpack version (example: 1.3.10)

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by MisherK5** [comment]
[latest.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9254939/latest.log)

**Comment by Kiri-Yoshikage** [comment]
какая сборка вообще? + лог неправильный, но его в комменты добавил. Короче пополни инфу, иначе тут ничего не разобрать

**Comment by Kiri-Yoshikage** [comment]
И, к слову, даже в комменте лог не тот лол

**Comment by AlgorithmLX** [comment]
> какая сборка вообще? + лог неправильный, но его в комменты добавил. Короче пополни инфу, иначе тут ничего не разобрать

По тегам смотри. MasterTech

**Comment by AlgorithmLX** [comment]
Хотя бы кто-нибудь будет читать куда логи выкладывать? НЕ ФАЙЛОМ, а на сайт gist.github.com или на тот же pastebin

**Comment by AlgorithmLX** [comment]
Где версия Сборки? Где версия форджа?

**Comment by AlgorithmLX** [comment]
В общем

**Comment by AlgorithmLX** [comment]
Закрываю как не достоверный

**Comment by Kiri-Yoshikage** [comment]
только щас теги заметил... но всё равно, инфы нифига нет, пусть пересоздаёт
