### ISSUE TITLE
Вылет игры

### ISSUE THREAD

**Issue by AngryKiT** [AlgorithmLX/LGameModpack-Issues#15]
Здравствуйте, я пишу по поводу вылета игры. Я играл в сборку 2 месяца и было все нормально. Но вчера когда я был в эндер мире и вышел из игры, а когда зашел в мир у меня аварийно закрылся мир по ошибке мода DummyCoreUnoffial. и с этого момента я не могу зайти в мир. Вот краш репорт. Надеюсь поможете, зарание спасибо.
[crash-2022-08-07_14.07.12-server.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9276738/crash-2022-08-07_14.07.12-server.txt)

**Comment by Kiri-Yoshikage** [comment]
не тот лог. Нужен latest.log. Скинь его, и можно будет уже попробовать посмотреть

**Comment by AlgorithmLX** [comment]
Заполните, так, как дано при создании

**Comment by AngryKiT** [comment]
[latest.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9276759/latest.log)
Вот этот?
