### ISSUE TITLE
Вылет игры

### ISSUE THREAD

**Issue by AngryKiT** [AlgorithmLX/LGameModpack-Issues#16]
Здравствуйте, я пишу по поводу вылета игры. Я играл в сборку 2 месяца и было все нормально. Но вчера когда я был в эндер мире и вышел из игры, а когда зашел в мир у меня аварийно закрылся мир по ошибке мода DummyCoreUnoffial. и с этого момента я не могу зайти в мир Надеюсь поможете, зарание спасибо

Logs:
[latest.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9276765/latest.log)

Minecraft Version: 1.12.2

Forge Version: there Forge version (example: 14.23.5.2860)

Modpack Version: there Modpack version (example: 1.5.8)

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by AlgorithmLX** [comment]
Блин,это надо с компа смотреть, ибо так просто не найду.

@HollowHorizon

**Comment by HollowHorizon** [comment]
В логах пишет, что DummyCore вообще отсутствует...

**Comment by AngryKiT** [comment]
Спасибо, но проблему уже решил. Я просто загрузил старый бекап и помогло. 
--
Отправлено из Mail.ru для Android четверг, 11 августа 2022г., 10:36 +03:00 от HollowHorizon  ***@***.*** :
