### ISSUE TITLE
черный экран при запуске мира в одиночке/локальный сервер

### ISSUE THREAD

**Issue by HatedInVoid** [AlgorithmLX/LGameModpack-Issues#17]
Здравствуйте столкнулся с проблемой когда захожу в мир на этой сборке постоянно висит черный экран что в одиночном режиме что по сети ждал пол часа и ничего не поменялось. Играл с друзьями в эту сборку пару месяцев назад и было все хорошо , а теперь черный экран постоянно что делать не знаю , все перепробовал. ПК мощный а сборка не работает у меня ((((((((((((( помогите пожалуйста

**Comment by AlgorithmLX** [comment]
Логи, всегда нужны логи.

**Тема закрыта.**
