### ISSUE TITLE
Крашится сервер

### ISSUE THREAD

**Issue by lonelesss** [AlgorithmLX/LGameModpack-Issues#18]
**** 

**Log
[crash-2022-08-25_09.13.44-fml.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9421315/crash-2022-08-25_09.13.44-fml.txt)
s:** There your logs from gist.github.com or log file(lasted.log)

**Version**

Minecraft: 1.16.5

Forge:forge-1.16.5-36.2.26.jar

Modpack: there Modpack version

//Don't touch me!

@BarMaxx

**Comment by AlgorithmLX** [comment]
@BarMaxx  ты где?

**Comment by BarMaxx** [comment]
Во-первых, извиняюсь за долгий ответ.
Во-вторых, удали моды totaldarkness и durability101. Эти моды сильно не поменяют геймплей, но из-за них нельзя запустить сервер.
