### ISSUE TITLE
oilcraft проблема с крафтом в quern

### ISSUE THREAD

**Issue by joketkill** [AlgorithmLX/LGameModpack-Issues#19]
quern из primalcore при крафте урушевого грунта(нужен любой вид травы плюс два цветка либо один большой) просто перемалывает цветок в краситель. Я написал автору мода, он сказал что разработкой модификаций больше не занимается, так что на вас одна надежда. КУстати если заменить цветок на хорус, то все хорошо, но я пока только на второй эпохе

**Comment by AlgorithmLX** [comment]
Сборка давно снята с поста обновлений.

**Тема закрыта.**
