### ISSUE TITLE
 Ошибка в квестах  Gloomy Rise1.0.0

### ISSUE THREAD

**Issue by Vebst0r** [AlgorithmLX/LGameModpack-Issues#20]
Gloomy Rise1.0.0
![image](https://user-images.githubusercontent.com/112538229/187604671-45e7c471-e997-4780-96a1-c2e5dd4f6e29.png)

**Comment by AlgorithmLX** [comment]
@barmaxx

**Comment by BarMaxx** [comment]
Знаю об этой ошибке, в обновлении будет исправлено.
