### ISSUE TITLE
Пропадают текст, иконки и текстуры

### ISSUE THREAD

**Issue by l0l174ch4n** [AlgorithmLX/LGameModpack-Issues#21]
Периодически при открытии инвентаря, сундука или чего-либо ещё, имеющего интерфейс, в т. ч. меню, полностью исчезают все иконки, текст и текстуры блоков. Потом всё возвращается после открытия нескольких других интерфейсов других объектов.
Проблема не решается перезапуском игры. Она возникла после прочтения "Кодекса Мага" и возникновения окошка маны и уровня в левом верхнем углу. До прочтения "Кодекса" ничего подобного не было.

@BarMaxx
[latest.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9485024/latest.log)
![OAtJXoYzsyY](https://user-images.githubusercontent.com/112818274/188322679-7abd8d5f-8e20-48db-917e-8f60687de432.jpg)

**Comment by Mrusi5** [comment]
Тоже столкнулся с этой проблемой. Заметил, что иконки и текст пропадают или меняют цвет, только при просмотре в определённом направлении. После смерти пропадает, но потом появляется опять. Направление после смерти меняется.

**Comment by AlgorithmLX** [comment]
@barmaxx

**Comment by BarMaxx** [comment]
Очень сильно извиняюсь, за то, что не ответил раньше.
Впервые вижу подобную проблему. Единственное, что могу посоветовать - переустановить сборку.

**Comment by AlgorithmLX** [comment]
Рассмотрено, закрыто.
