### ISSUE TITLE
Error when entering the world

### ISSUE THREAD

**Issue by Mideenek** [AlgorithmLX/LGameModpack-Issues#22]
**Description:**: When entering the game, an error crashes and the world closes. Mistake:Essentical Craft4 Unoffical, Hammer Core.

**Logs:** There your logs from gist.github.com or log file(lasted.log)

Minecraft Version: 1.12.2

Forge Version: 14.23.5.2855

Modpack Version: 1.4.8

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon
[crash-2022-09-13_18.54.39-server.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/9557783/crash-2022-09-13_18.54.39-server.txt)

**Comment by Kiri-Yoshikage** [comment]
(если ты на русском говоришь - пиши на русском. Пока не знаю, отвечу лучше на английском)

Wrong log. We need "Latest.log" from crash-reports folder. But i can say that if its because essential - try to reinstall modpack or load backup. EC4 is bugged as shit, so this is kinda normal. Do you have nature furnace?

**Comment by Mideenek** [comment]
Да я ставил природную печь, после этого и вылетело.

**Comment by Mideenek** [comment]
> Wrong log. We need "Latest.log" from crash-reports folder. But i can say that if its because of essential - try to reinstall modpack or load backup. EC4 is bugged as shit, so this is kinda normal. Do you have nature furnace?



> (если ты на русском говоришь - пиши на русском. Пока не знаю, отвечу лучше на английском)
> 
> Wrong log. We need "Latest.log" from crash-reports folder. But i can say that if its because of essential - try to reinstall modpack or load backup. EC4 is bugged as shit, so this is kinda normal. Do you have nature furnace?

Да природная печь было, после неё и вылетело.

**Comment by Kiri-Yoshikage** [comment]
в ней скорее всего дело, она оч баганная. Попробуй откатится до бекапа где ты ещё не построил печь(если это было не слишком давно) и построй её где-то далеко. Или просто переустанови сборку и помолись
