### ISSUE TITLE
Нет звука в игре

### ISSUE THREAD

**Issue by Ded666mityai** [AlgorithmLX/LGameModpack-Issues#23]
Нет игровых звуков, ни блоков, ни мобов ни музыки, только звук "окружения"(птички поют) и мелодия квеста, даже кнопки в меню нажимаются бесшумно. Проблема только на этой сборке. Качал через лаунчер

**Version**

Minecraft: 1.16.5

Forge: there Forge version

Modpack: there Modpack version

//Don't touch me!

@BarMaxx

**Comment by Kiri-Yoshikage** [comment]
Как бы глупо не звучало - но проверь настройки звука. Часто ловил себя на мысли, что пару часов играю без звука. Хотя на самом деле это скорее всего баг лаунчера, ведь он ещё в довольно раннем релизе и багов может быть довольно много. Если в настройках игры всё будет ок - отправь Shinovon#5881 в дискорде в личные сообщения.

**Comment by Ded666mityai** [comment]
> Как бы глупо не звучало - но проверь настройки звука. Часто ловил себя на мысли, что пару часов играю без звука. Хотя на самом деле это скорее всего баг лаунчера, ведь он ещё в довольно раннем релизе и багов может быть довольно много. Если в настройках игры всё будет ок - отправь Shinovon#5881 в дискорде в личные сообщения.

В настройках то все норм, пробовал даже гуглить и пытаться решить проблему, не помогло, все драйвера новые, другие майнкрафты работают

**Comment by shinovon** [comment]
Проблема скорее всего в лаунчере, я недавно поменял метод скачивания ассетов.

**Comment by AlgorithmLX** [comment]
Рассмотрено, закрыто
