### ISSUE TITLE
Minecraft Server start - strange issue

### ISSUE THREAD

**Issue by NotEklerchik** [AlgorithmLX/LGameModpack-Issues#24]
**Description:** Immediately after starting the server, it stops for no clear reason (It outputs only three lines in the console). Perhaps it has something to do with the mod mastertech-1.0.jar , it cannot download something and automatically shuts down the server, since the computer does not have direct access to the global network (I use a separate computer for the server). Can I somehow solve this problem without providing the server with Internet access to download files, or are there no other options?

**Logs:** 
```
[19:54:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:54:02] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:54:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
```

Minecraft Version: 1.12.2

Forge Version: Forge version forge-1.12.2-14.23.5.2860

Modpack Version: v1.5.8-Finally

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by HollowHorizon** [comment]
Так, ну судя по нику ты понимаешь русский, так что можешь сразу на нём и писать)
насчёт сервера, лучше скачай тот что у нас в дискорде и замени конфиги и скрипты из последней версии сборки, там уже всё настроено и должно работать. mastertech-1.0.jar тут вообще ни при чём, он просто добавляет пару новых предметов и прекрасно работает и на сервере

**Comment by AlgorithmLX** [comment]
Рассмотрено, закрыто
