### ISSUE TITLE
Проблема с квестами

### ISSUE THREAD

**Issue by wizardy28** [AlgorithmLX/LGameModpack-Issues#29]
**Description:** Please, provide this description!!!

**Logs:** There your logs from gist.github.com or log file(lasted.log)

Minecraft Version: 1.12.2

Forge Version: there Forge version (example: xx.xx.x.xxx)

Modpack Version: there Modpack version (example: 1.3.10)

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by wizardy28** [comment]
Играю с другом в мире, на следующий день, после захода в игру, откатились квесты, как их вернуть?

**Comment by wizardy28** [comment]
Эта команда позволяет настраивать квесты, ей же можно и выполнять их? Или как это работает?

**Comment by Kiri-Yoshikage** [comment]
И то, и то. Она даёт возможность их менять, создавать, выполнять и т.д. С другом сравниваете квесты, и выполняешь всё до последнего. Для этого нужно нажать пкм по квесту, и в контекстном меню выбрать пункт

**Comment by AlgorithmLX** [comment]
> Эта команда позволяет настраивать квесты, ей же можно и выполнять их? Или как это работает?

Можно настраивать и выполнять. После восстановления квестов, которые Вы выполнили, прописываете: /ftbquests editing_mode false. На такие случаи, существуют бекапы.

Рассмотрено, закрыто
