### ISSUE TITLE
Крашит игру при запуска маинкрафта

### ISSUE THREAD

**Issue by 1RoFlan1** [AlgorithmLX/LGameModpack-Issues#30]
**Description:** Please, provide this description!!!

**Logs:** There your logs from gist.github.com or log file(lasted.log)
[crash-2022-11-18_12.57.54-client.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/10040365/crash-2022-11-18_12.57.54-client.txt)

Minecraft Version: 1.12.2

Forge Version: there Forge version (example: xx.xx.x.xxx) 14.23.5.2860

Modpack Version: there Modpack version (example: 1.3.10)

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

![image](https://user-images.githubusercontent.com/118526227/202680790-050a52c8-6e22-48b8-b2cf-05687e439bb5.png)

**Comment by HollowHorizon** [comment]
Хм, похоже на то, что сборка была установлена не правильно и не удалены все файлы в папке с игрой перед установкой сборки. Попробуй переустановить

**Comment by 1RoFlan1** [comment]
так прикол в том, что играю уже неделю, и вот запускай маинкрафт и выбивает с такой ошибкой

**Comment by HollowHorizon** [comment]
хм, ну тогда сохрани копию мира и попробуй переустановить сборку, вероятно это будет самым быстрым решением

**Comment by AlgorithmLX** [comment]
Рассмотрено, закрыто
