### ISSUE TITLE
2 мода не указаны как обновлённые

### ISSUE THREAD

**Issue by Kiri-Yoshikage** [AlgorithmLX/LGameModpack-Issues#31]
После запуска сборки игра крашила из-за дюпа модов. Ошибка оказалась за мной - я забыл очистить моды. Начал вручную перебирать моды, точнее через поиск убирать все копии обновлённых модов. Всё было отлично, но когда я проверил каждый мод - всё равно крашило. Перебрав вручную всю папку модс я нашёл самую ужасную ошибку из всех! Какой ужас! Какой кошмар! 2 мода не указаны как обновлённые в Gloomy Rise update.txt! Автора на мыло!!!
а вообще я шучу. Дико мелкая ошибка, но на всякий случай напишу сюда, т.к. некоторым людям это слишком важно... #Макс_Исправь_Если_Время_Будет
Вот кстати сами моды: Legendary Tooltips; supermartijn642configlib(он так и называется в папке модов :kek:)

Minecraft: 1.16.5

Forge: хз если честно

Modpack: GR v1.1.187

//зачем я это написал...

@BarMaxx

**Comment by Kiri-Yoshikage** [comment]
Хм, теперь тут даже на мою ошибку не списать... Если второй мод просто не указан, то лт вообще подписан как удалённый. Хотя в папке просто появилась новая версия. Короче сорян что придираюсь, но просто по приколу решил написать)

**Comment by BarMaxx** [comment]
Так, у меня как раз 1 мод куда-то потерялся, хорошо, что нашел его(я потом сам посмотрю, вдруг просто ты невнимательный). Насчёт Legendary Tooltips - он удален из сборки, скорее всего я просто забыл убрать его из списка обновленных, так как сначала я его обновил, а потом удалил :)
