### ISSUE TITLE
Краш при поиске в REI

### ISSUE THREAD

**Issue by Kiri-Yoshikage** [AlgorithmLX/LGameModpack-Issues#32]
Если мой прошлый "репорт" был скорее шуткой, то тут действительно неприятная проблема. При каждом поиске предметов в рей игра крашит - просто зависает через пару секунд и закрывается. Не тестировал версии форджа, но с версией жабы всё в порядке - последняя. В настройках мода ничего по этому поводу не нашёл. Так же заметил, что крашит как-то через раз. Точнее  в 9/10 раз. Странная тема, в общем

Logs: чисто на всякий пожарный дам все логи что есть

[crash-2022-12-19_10.46.12-client.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/10258178/crash-2022-12-19_10.46.12-client.txt)
[latest.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/10258180/latest.log)
[rei.log](https://github.com/AlgorithmLX/LGameModpack-Issues/files/10258181/rei.log)

Minecraft: 1.16.5

Forge: последняя версия фордж 1.16.5

Modpack: v1.1.187

//пачинити пазязя

@BarMaxx

**Comment by BarMaxx** [comment]
Как я понял, несколько модов (REI и ModernUI) конфликтуют и из-за этого происходит такой краш. Скоро будет обновление, исправлю это.
