### ISSUE TITLE
крашит майнкрафт при запуске 

### ISSUE THREAD

**Issue by awatella** [AlgorithmLX/LGameModpack-Issues#35]
при загрузке майнкрафта вылетает ошибка запуска из-за мода EssentialCraft 4 Unofficial
[crash-2023-01-03_16_29_19-client.txt](https://github.com/AlgorithmLX/LGameModpack-Issues/files/10336983/crash-2023-01-03_16_29_19-client.txt)
может ли кто нибуть помочь?

**Comment by AlgorithmLX** [comment]
Оформление по форме
