### ISSUE TITLE
Pack fails to start up on ATLauncher

### ISSUE THREAD

**Issue by DecoDragon** [AlgorithmLX/LGameModpack-Issues#36]
**Description:** Please, provide this description!!!
Pack fails to start up on ATLauncher

**Logs:** There your logs from gist.github.com or log file(lasted.log)
https://paste.atlauncher.com/view/4fc30924-0846-42c9-aafd-acc478c63e56

Minecraft Version: 1.12.2

Modpack Version: 1.5.8.2

//Don't touch me!!!

@AlgorithmLX,
@HollowHorizon

**Comment by AlgorithmLX** [comment]
Hello! I am aware of this problem. Of the solutions, I can only recommend the following:
1. Disable Windows Firewall 
2. Add java.exe to exceptions in your antivirus settings (if available).

This is the only thing I can offer for now

**Comment by AlgorithmLX** [comment]
Hello! I am aware of this problem. Of the solutions, I can only recommend the following:
1. Disable Windows Firewall 
2. Add java.exe to exceptions in your antivirus settings (if available).

This is the only thing I can offer for now

**Comment by AlgorithmLX** [comment]
This problem can be solved by installing [this version](https://cdn.azul.com/zulu/bin/zulu8.78.0.19-ca-jre8.0.412-win_x64.msi) of Java. There are no other solutions
