### ISSUE TITLE
Миникравт вылитает(9((

### ISSUE THREAD

**Issue by HollowHorizon** [AlgorithmLX/LGameModpack-Issues#5]
**Modpack:** Тут просто 3 мода.

**Description:** У меня вылитит игра, памагити(((9

**Logs:** [логи тута](https://github.com/AlgorithmLX/LGameModpack-Issues/files/8886499/crash-2022-04-30_10.02.07-client.txt)

**Version** 1.0

Minecraft: 1.16.5

Forge: HML_36.2 [скачивал тут](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

Modpack: 1.0

**Comment by Kiri-Yoshikage** [comment]
А потом оказывается, что в логах вирус...

**Comment by HollowHorizon** [comment]
Ты что блин, не пали меня!

**Comment by AlgorithmLX** [comment]
Топ вопрос

**Comment by HollowHorizon** [comment]
Блин, это что получается... я правила нарушил и их написали раньше моего сообщения(

**Comment by Kumizi** [comment]
`Java Version: 19.8.0_181, Hollow Corporation`
охренеть

**Comment by AlgorithmLX** [comment]
С ума уже сходишь, со своим Hollow Core

**Comment by AlgorithmLX** [comment]
![IMG_20220613_013906](https://user-images.githubusercontent.com/46783751/173248326-8e2239d3-b1df-44f4-b988-b2770ea5d842.jpg)

**Comment by HollowHorizon** [comment]
Это да, а какой процессор...

**Comment by AlgorithmLX** [comment]
Intel Core I3 хз какой

**Comment by AlgorithmLX** [comment]
Вас спалили

**Comment by HollowHorizon** [comment]
![image](https://user-images.githubusercontent.com/78298979/173248656-28c8ab78-16e0-47a4-824e-b7270635ac34.png)
Ты что, какой I3))

**Comment by AlgorithmLX** [comment]
А логи что, переписывать нельзя?😎

**Comment by AlgorithmLX** [comment]
Так, все. Закрываю обсуждение, пошутили и хватит
