### ISSUE TITLE
Don't crafting null item

### ISSUE THREAD

**Issue by AlgorithmLX** [AlgorithmLX/LGameModpack-Issues#7]
**Description:** Не крафтится null предмет

**Logs:** Он здесь не нужен

**Version**

Minecraft: 1.16.5

Forge: 36.2.35

Modpack: 1.0

**Comment by Kiri-Yoshikage** [comment]
что бы получить null, нужно в джаве написать прогу, которой нечего выводить в консоль. Вопрос решён:sunglasses:

**Comment by AlgorithmLX** [comment]
Real

**Comment by AlgorithmLX** [comment]
Спасибо

**Comment by AlgorithmLX** [comment]
Heh

**Comment by HollowHorizon** [comment]
Ну так добавь ему крафт, ты же мододел)

**Comment by AlgorithmLX** [comment]
Тестировка полного логирования

**Comment by AlgorithmLX** [comment]
Удачно

**Comment by AlgorithmLX** [comment]
> Ну так добавь ему крафт, ты же мододел)

Ахахах, точно
