### ISSUE TITLE
Пропали крафты 

### ISSUE THREAD

**Issue by x7vn** [AlgorithmLX/LGameModpack-Issues#8]
**Description:** Пропали крафты половины предметов. Сборку переустанавливал полностью 3 раза, все эры открыты 

**Logs:** логов нет

**Version** 

Minecraft: 1.12.2
Forge: 14.23.5.2860
Modpack: 1.4.8

**Comment by AlgorithmLX** [comment]
так-так. откуда скачана сборка?

**Comment by x7vn** [comment]
https://minecraft-inside.ru/modpacks/139989-mastertech-tehno-magiya-i-rpg.html

**Comment by x7vn** [comment]
Да

**Comment by AlgorithmLX** [comment]
[scripts.zip](https://github.com/AlgorithmLX/LGameModpack-Issues/files/8909681/scripts.zip)

**Comment by AlgorithmLX** [comment]
книги используйте

**Comment by AlgorithmLX** [comment]
что за крафт-то?

**Comment by AlgorithmLX** [comment]
для монет - крафт отключен

**Comment by HollowHorizon** [comment]
В чате ошибки есть? Какие-либо изменения в сборке делали? Моды там удаляли или что-то ещё

**Comment by x7vn** [comment]
![image](https://user-images.githubusercontent.com/74578736/173880788-57fcd09e-27b5-40fd-86a6-5d2123f791c8.png)

**Comment by x7vn** [comment]
Поменяли карту, добавили 2 мода

**Comment by AlgorithmLX** [comment]
Удалял Essential craft?

**Comment by x7vn** [comment]
xaeros minimap только удалял

**Comment by HollowHorizon** [comment]
Интересно... игра не может найти предмет из MorePlates... если сам мод установлен, то всё-таки что-то не то ты удалил... как вариант ещё раз переустанови по инструкции или попробуй включить редстоун шестерёнку в конфиге MorePlates

**Comment by x7vn** [comment]
Переустановка не помогла

**Comment by x7vn** [comment]
Я уже переустанавливал полностью игру

**Comment by x7vn** [comment]
и отдельно папку со скриптами

**Comment by x7vn** [comment]
![1](https://user-images.githubusercontent.com/74578736/174108011-32857b5c-6722-48a4-84de-9b2341c17d5a.PNG)
![2](https://user-images.githubusercontent.com/74578736/174108070-5df769f2-e11b-4814-9916-c1fbd8f274b6.PNG)
![3](https://user-images.githubusercontent.com/74578736/174108088-ae12abb3-68dc-4c95-88a6-7578325a660f.PNG)
![4](https://user-images.githubusercontent.com/74578736/174108121-c0867acc-5af7-40c9-9e5d-20d5f3ceb7f6.PNG)
![5](https://user-images.githubusercontent.com/74578736/174108140-d5445356-6b65-4bc1-bfca-345f70ed258b.PNG)

**Comment by HollowHorizon** [comment]
Хм, как странно... ладно, минутку
![image](https://user-images.githubusercontent.com/78298979/174117367-73142c51-e777-47e8-8dd1-00d0aacd95db.png)
![image](https://user-images.githubusercontent.com/78298979/174117397-ac0071f5-a360-46ea-93fe-5dee62326a09.png)

**Comment by x7vn** [comment]
Спасибо, крафты появились
