### ISSUE TITLE
При старте сервера моды обращаются к client-side классам.

### ISSUE THREAD

**Issue by NikKeY7** [AlgorithmLX/LGameModpack-Issues#9]
Скриншот: https://media.discordapp.net/attachments/822157545622863905/988055286839378000/unknown.png?width=916&height=91

Решили запустить сервер со сборкой EndlessRise. Однако следующие моды выдают данные ошибки.

**Comment by AlgorithmLX** [comment]
я для кого форму делал? Описание есть, а логи где?
![image](https://user-images.githubusercontent.com/46783751/174481032-7be2dbcb-cd2f-47df-938d-a5ca1da2c732.png)

**Comment by BarMaxx** [comment]
Вообще, 2 и 3 моды можете спокойно удалять так как они ни на что не влияют, но вот предметы magical wings используются в нескольких крафтах. Можете попробовать либо удалить эти крафты, либо заменить предметы.

**Comment by NikKeY7** [comment]
Дополнение

Logs: [Ссылка](https://drive.google.com/file/d/1CZrreloDnL0ZAr_aGPMuf4n-On9eQHk3/view?usp=sharing)

Minecraft: 1.16.5

Forge: 36.2.26

Modpack: v1.1.12

**Comment by AlgorithmLX** [comment]
По одному краш логу нечего не поймешь. Перейди в папку logs и из lasted.log(открой обычным блокнотом) залей на gist.github.com, только откройте его для публичного просмотра

**Comment by HollowHorizon** [comment]
![image](https://user-images.githubusercontent.com/78298979/174649580-be33934f-532a-4099-b70f-c32a3c9c345c.png)
учитывая, что это клиентские моды, на сервере им не место, просто удалите их

**Comment by AlgorithmLX** [comment]
Если ответа нет более одного дня, или вопрос решен, то ветка закрывается

**Comment by Lokilife** [comment]
> ![image](https://user-images.githubusercontent.com/78298979/174649580-be33934f-532a-4099-b70f-c32a3c9c345c.png) учитывая, что это клиентские моды, на сервере им не место, просто удалите их

Magical Wings не совсем клиентский мод, но можно просто закинуть его более новую версию и всё заводится.
